name: release-feedback
description: >-
  Add content to your GitHub release description from your release workflow.
inputs:
  content:
    description: >-
      A string to append to the release description.  The release description
      is in markdown.  A newline will be added automatically before this line
      is added.
    required: true
  release:
    description: >-
      Use `github.event.release.id`.
    required: true
  token:
    description: >-
      Use `secrets.GITHUB_TOKEN` or any other valid auth token from GitHub.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'rss'
  color: 'blue'