name: release-feedback
description: >-
  Add content to your GitHub release description from your release workflow.
inputs:
  content:
    description: >-
      A string to append to the release description.  The release description
      is in markdown.  A newline will be added automatically.
    required: true
  release:
    description: >-
      The release id.  Use ${{ github.event.release.id }}.
    required: true
  token:
    description: >-
      A token for authenticating to GitHub.  Uses ${{ secrets.GITHUB_TOKEN }}
      if not declared.
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'