# note use "jeking3/release-feedback@v1" instead of "./" for production
# this example also helps me test changes
---
name: example
on:
  release:
    types:
      - published

env:
  SOME_DOCKER_IMAGE: docker/foobar:v.awesome

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Promote env to output
        id: promote
        run: echo "::set-output name=image::${SOME_DOCKER_IMAGE}"
      - uses: ./
        with:
          content: "### Build Status"
          release: ${{ github.event.release.id }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        with:
          content: "- Beginning Build"
          release: ${{ github.event.release.id }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        with:
          content: "- Build Complete!  Fictitiously pushed to ${{ steps.id.image }}"
          release: ${{ github.event.release.id }}
          token: ${{ secrets.GITHUB_TOKEN }}