# note use "jeking3/release-feedback@v1" instead of "./" for production
# this example also helps me test changes
---
name: example
on:
  release:
    types:
      - published

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          content: "### Build Status"
      - uses: ./
        with:
          content: "- Beginning Build"
      - uses: ./
        with:
          content: "- Build Complete!"
